version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next-auth
    versions:
    - 3.11.1
    - 3.11.2
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.14.7
    - 3.15.13
    - 3.15.9
    - 3.17.2
    - 3.18.0
    - 3.2.1
    - 3.4.1
    - 3.4.2
    - 3.5.0
    - 3.5.1
    - 3.6.0
    - 3.6.1
    - 3.7.0
  - dependency-name: postcss
    versions:
    - 8.2.12
    - 8.2.5
    - 8.2.6
    - 8.2.7
  - dependency-name: next
    versions:
    - 10.0.7
    - 10.0.8
